name: deepseek-lite
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.2.1
  - pip
  - pip:
      - numpy==1.24.4
      - tqdm==4.66.2
      - transformers==4.40.1
      - datasets==2.19.1
